<?php
session_start(); // Start the session to access session variables
include("Mysqlconnection.php");
require 'PHPMailer/src/PHPMailer.php';
require 'PHPMailer/src/SMTP.php';
require 'PHPMailer/src/Exception.php';

use PHPMailer\PHPMailer\PHPMailer;

// Function to check if dates overlap
function datesOverlap($start1, $end1, $start2, $end2) {
    return $start1 <= $end2 && $start2 <= $end1;
}

// Function to send email
function sendReservationEmail($to, $subject, $body) {
    $mail = new PHPMailer;
    $mail->isSMTP();
    $mail->Host = 'smtp.gmail.com';
    $mail->SMTPAuth = true;
    $mail->Username = 'denuwansathsara0412@gmail.com';
    $mail->Password = 'boaa moki kmax yzyz';
    $mail->SMTPSecure = 'ssl';
    $mail->Port = 465;

    $mail->setFrom('denuwansathsara0412@gmail.com', 'Denuwan');  
    $mail->addAddress($to);

    $mail->isHTML(true);
    $mail->Subject = $subject;
    $mail->Body    = $body;

    return $mail->send();
}

if (isset($_POST['submit'])) {
    $checkin = $_POST['checkin'];
    $checkout = $_POST['checkout'];
    $persons = $_POST['persons'];
    $requests = $_POST['requests'];

    // Convert dates to YYYY-MM-DD format if needed
    $checkin = date('Y-m-d', strtotime($checkin));
    $checkout = date('Y-m-d', strtotime($checkout));

    // Extract the year from the check-in date
    $checkinYear = date('Y', strtotime($checkin));

    // Retrieve the EmployeeID from the session
    if (isset($_SESSION['EmployeeID'])) {
        $EmployeeID = $_SESSION['EmployeeID'];

        // Check if the user has a pending reservation
        $pendingReservationQuery = "
            SELECT COUNT(*) as pending_count 
            FROM reservations 
            WHERE EmployeeID = '$EmployeeID'";

        $pendingReservationResult = mysqli_query($connection, $pendingReservationQuery);
        $pendingReservationRow = mysqli_fetch_assoc($pendingReservationResult);

        if ($pendingReservationRow['pending_count'] > 0) {
            // If the user has a pending reservation, show an alert
            echo '<script>
                alert("You already have a pending reservation.");
                window.location.href="index.php";
            </script>';
            exit();
        }

        // Check how many completed reservations the user has for the year of check-in
        $completedReservationsQuery = "
            SELECT COUNT(*) as completed_count 
            FROM reservationhistories 
            WHERE EmployeeID = '$EmployeeID' 
              AND status = 'Completed' 
              AND YEAR(checkin) = '$checkinYear'";

        $completedReservationsResult = mysqli_query($connection, $completedReservationsQuery);
        $completedReservationsRow = mysqli_fetch_assoc($completedReservationsResult);

        if ($completedReservationsRow['completed_count'] >= 2) {
            // If the user has 2 or more completed reservations this year, show an alert
            echo '<script>
                alert("You have reached the maximum number of bookings this year.");
                window.location.href="index.php";
            </script>';
            exit();
        }

        // Proceed to check for availability and make the booking
        $sql = "SELECT checkin, checkout FROM reservations";
        $result = mysqli_query($connection, $sql);

        if ($result) {
            $isAvailable = true;

            while ($row = mysqli_fetch_assoc($result)) {
                $existingCheckin = $row['checkin'];
                $existingCheckout = $row['checkout'];

                if (datesOverlap($checkin, $checkout, $existingCheckin, $existingCheckout)) {
                    $isAvailable = false;
                    break;
                }
            }

            if ($isAvailable) {
                // Insert the new reservation if available, including EmployeeID
                $sql = "INSERT INTO reservations (EmployeeID, checkin, checkout, persons, requests) 
                        VALUES ('$EmployeeID', '$checkin', '$checkout', '$persons', '$requests')";
                $result = mysqli_query($connection, $sql);

                if ($result) {
                    // Get the autogenerated invoice number
                    $invoicenumber = mysqli_insert_id($connection);

                    // Fetch the user's email
                    $userEmailQuery = "SELECT Email FROM users WHERE EmployeeID = '$EmployeeID'";
                    $userEmailResult = mysqli_query($connection, $userEmailQuery);
                    if ($userEmailResult && mysqli_num_rows($userEmailResult) > 0) {
                        $userEmailRow = mysqli_fetch_assoc($userEmailResult);
                        $userEmail = $userEmailRow['Email'];

                        // Prepare email content
                        $subject = "Reservation Confirmation";
                        $body = "<h1>Reservation Confirmed</h1>
                                 <p>Dear Guest,</p>
                                 <p>Your reservation is confirmed.</p>
                                 <p><strong>Invoice Number:</strong> $invoicenumber</p>
                                 <p><strong>Check-in:</strong> $checkin</p>
                                 <p><strong>Check-out:</strong> $checkout</p>
                                 <p><strong>Number of Guests:</strong> $persons</p>
                                 <p><strong>Special Requests:</strong> $requests</p>";

                        // Send the email
                        if (sendReservationEmail($userEmail, $subject, $body)) {
                            echo '<script>
                                    alert("Booking successful! Confirmation email sent.");
                                    window.location.href="index.php";
                                </script>';
                        } else {
                            echo '<script>
                                    alert("Booking successful, but failed to send confirmation email.");
                                    window.location.href="index.php";
                                </script>';
                        }
                    } else {
                        echo '<script>alert("Error fetching user email. Please try again.");</script>';
                    }
                } else {
                    echo '<script>alert("Error while booking. Please try again.");</script>';
                }
            } else {
                echo '<script>
                alert("Selected dates are already reserved. Please choose different dates.");
                window.location.href="Booking.php";
                </script>';
            }
        } else {
            echo '<script>alert("Error fetching reservations. Please try again.");</script>';
        }
    } else {
        echo '<script>alert("EmployeeID not found in session. Please log in again.");</script>';
    }
}
?>
